### ISSUE TITLE
Wrong version of io.reactivex.rxjava3:rxjava

### ISSUE THREAD

**Issue by paulgallagher75** [vert-x3/vertx-infinispan#102]
https://github.com/vert-x3/vertx-infinispan/blob/34347531ce76990a3af7737d76225caffb5952b8/vertx-web-sstore-infinispan/pom.xml#L102

its currently 3.0.9 when all other places in vertx modules like vertx-rx and vertx-infinispan have it as 3.0.13, as its used in 2 submodules of vertx-infinispan-parent I would add the 3.0.13 version to that in the dependencyManagement section for use in  vertx-infinispan and vertx-web-sstore-infinispan, or if we want to keep this the same version across all vertx modules as the comment above the dependency suggests we should add it to the BOM vertx-dependencies

**Comment by tsegismont** [comment]
Thank you @paulgallagher75 for the heads-up.

I put the ISPN version in a parent POM property
