### ISSUE TITLE
entryStream() throws an exception

### ISSUE THREAD

**Issue by ruslansennov** [vert-x3/vertx-infinispan#106]
Converting infinispan's entryStream to kotlin's ReceiveChannel throws an exception:
```
java.lang.NullPointerException: Cannot invoke "org.infinispan.commons.util.CloseableIteratorCollection.iterator()" because "this.iterable" is null
	at io.vertx.ext.cluster.infinispan.impl.CloseableIteratorCollectionStream.lambda$doRead$2(CloseableIteratorCollectionStream.java:134)
```
This can be reproduced by adding `stream.fetch(1)` to the very last line of the loadData callback (like it does in the `ReadStream<T>.toChannel()`) in `InfinispanClusteredAsyncMapTest` (reproduces occasionally).

I'll provide a PR to fix this soon.

**Comment by tsegismont** [comment]
Thank you!
