### ISSUE TITLE
Why do you use Infinispan

### ISSUE THREAD

**Issue by HelloTo4x** [vert-x3/vertx-infinispan#115]
Hi, i am reading your project, why do you use Infinispan for caching instead of Redis, can you tell me why you choose it, and the pros and cons of this, thank u so much

**Comment by tsegismont** [comment]
We use Infinispan for Vert.x clustering because it provides node discovery and membership management. Redis doesn't.

We have alternatives to this cluster manager: `vertx-hazelcast`, `vertx-ignite` and `vertx-zookeeper`>
