### ISSUE TITLE
Current Infinspan version (13.0.10) incompatible to Quarkus

### ISSUE THREAD

**Issue by pk-work** [vert-x3/vertx-infinispan#118]
Vert.x 4.3.7 is using Infinispan version 13.0.12.Final [1].
The current Quarkus version is using Infinispan version 14.0.4 Final [2].

It seems that these Infinispan versions have incompatible versions of JGoups, which prevents Infinispan from creating a cluster.

What is the next Vert.x version that would allow the Infinispan version to be updated?

[1] https://github.com/vert-x3/vertx-infinispan/blob/master/pom.xml#L33
[2] https://mvnrepository.com/artifact/io.quarkus/quarkus-bom/2.15.2.Final

**Comment by pmlopes** [comment]
@tsegismont maybe we need to align this with Quarkus to avoid breakages.

**Comment by tsegismont** [comment]
We cannot upgrade to ISPN 14 while we have the Java 8 baseline. This could be possible in Vert.x 5

**Comment by pk-work** [comment]
Thanks for clarification, that's good to know

**Comment by tsegismont** [comment]
Resolved by #129
