### ISSUE TITLE
Update to Infinispan 14 in Vert.x 5

### ISSUE THREAD

**Issue by pk-work** [vert-x3/vertx-infinispan#129]
Vert.x 5 should support the latest Infinispan version, which is at the moment Infinispan 14.

This change has the potential to be breaking, because since Infinispan 14 they switched from JavaEE to Jakarta [1].

> JavaEE is dead. Long-live [JakartaEE](https://jakarta.ee/). Wherever we used to depend on javax APIs, we now depend on their jakarta equivalent. We still provide compatibility artifacts for legacy deployments.

Even if they support a JavaEE package for 14, it seems they are not longer supported in Infinispan 15. So we should go for the Jakarta package.

[1] https://infinispan.org/blog/2022/05/30/infinispan-14

**Comment by tsegismont** [comment]
I think we can go with ISPN-14-jakarta. This is what's used in Quarkus as well, correct? That would help solving #118 too.

Can you work on this any time soon @pk-work ?

Eventually, if ISPN-15 is released before Vert.x 5, we can upgrade to this version

**Comment by tsegismont** [comment]
Btw, when this is implemented, we should have a note added in the breaking changes wiki page.

**Comment by pk-work** [comment]
> Can you work on this any time soon @pk-work ?

I think I can do it next week or the week after, is this soon enough? Is it urgent?

@tsegismont

**Comment by tsegismont** [comment]
This is fine, thank you.
