### ISSUE TITLE
Check the Openshift setup with Infinispan 9 implementation

### ISSUE THREAD

**Issue by tsegismont** [vert-x3/vertx-infinispan#18]
Master branch is now based on Infinispan 9. We must check that the documentation section about Openshift is correct.

**Comment by tsegismont** [comment]
https://github.com/vert-x3/vertx-infinispan/blob/master/src/main/asciidoc/java/index.adoc#configuring-for-openshift-3

**Comment by cescoffier** [comment]
@tsegismont Should I have a look ?

**Comment by cescoffier** [comment]
Looking at the doc I'm a bit worried it would not be usable using a S2I build (without some tweaks). We may have to change the Fabric8 Vert.x generator to simplify the settings.

**Comment by tsegismont** [comment]
Sure. The JGroups config file in the project has been updated, but the
Openshift version printed in docs hasn't.

BTW, it may be better to add a file to project, and use Asciidoctor
includes.

2017-02-13 8:06 GMT+01:00 Clement Escoffier <notifications@github.com>:

**Comment by tsegismont** [comment]
Also, jgroups-kubernetes has a new version 0.9.1. We should probably
upgrade.

2017-02-13 10:23 GMT+01:00 Thomas SEGISMONT <tsegismont@gmail.com>:

**Comment by tsegismont** [comment]
Not sure what you mean. Can you elaborate?

2017-02-13 8:35 GMT+01:00 Clement Escoffier <notifications@github.com>:

**Comment by cescoffier** [comment]
From the current doc, it needs:

* an ENV variables not provided by the S2I
* a specific Java system property (IPv4)
* opening another port (that would also change the service creation as we need to select the right one)

These 3 tasks are not handled by the regular Java S2I that is recommended in OpenShift for Java applications packaged as fat jar. As docker/binary build are not supported by all Openshift instances (for security reason), it would be very hard to deploy a Vert.x app with Infinispan (typically Openshift online does not allow binary build).

**Comment by tsegismont** [comment]
Got you.

I'm surprised the S2I mechanism doesn't take env vars and sysprops into
account since they're pretty common for running Docker/Java apps. Do you
know what should be used with S2I to send parameters for runtime.
We can also talk with the maintainers of JGroups Kubernetes to determine if
there's another way to configure the KUBE_PING namespace.

2017-02-13 10:32 GMT+01:00 Clement Escoffier <notifications@github.com>:

**Comment by cescoffier** [comment]
So about the KUBE_PING Namespace, yes there is another way (https://github.com/vert-x3/vertx-service-discovery/blob/master/vertx-service-discovery-bridge-kubernetes/src/main/java/io/vertx/servicediscovery/kubernetes/KubernetesServiceImporter.java#L161).


The S2I allows you to configure env variables. However, configuring them in the fabric8 maven plugin is not that easy. About system properties, you would need to configure the full command line (I need to check this - never did it by myself).

**Comment by tsegismont** [comment]
Verified manually
