### ISSUE TITLE
Align lock implementation with other cluster managers 

### ISSUE THREAD

**Issue by tsegismont** [vert-x3/vertx-infinispan#19]
This cluster manager uses JGroups locks. But Vert.x locks are not distributed locks, they are distributed semaphores with a single permit.

The JGroups locks have been configured to not use the thread id for lock owner. This allows to release the lock from a different thread.
But it also allows to acquire the same lock twice if you're on the same JVM. Two tests from the suite have been disabled because of this (`InfinispanClusteredAsynchronousLockTest#testAcquireOnSameEventLoop` and `InfinispanClusteredAsynchronousLockTest#testAcquireOnExecuteBlocking`).

**Comment by karesti** [comment]
@tsegismont clustered locks have been integrated for the 9.2 beta

**Comment by karesti** [comment]
https://github.com/vert-x3/vertx-infinispan/pull/39
