### ISSUE TITLE
Clustered mode eventbus messaging seems incredibly slow

### ISSUE THREAD

**Issue by jeacott1** [vert-x3/vertx-infinispan#33]
I have a little test app, running vertx 3.4.1 and a range of cluster managers.

I'm using the infinispan manager out of the box, no special config running on a single box, clustered mode sending 50,000 short text messages (just the current message number actually - ie 1, 2 ,3 ,4...50000) between 2 verticles.

time to send all 50k is 19ms
time from first received msg to last received message is ~45seconds!!
this seems to scale fairly linearly and is fully 10 fold worse than the next slowest which is hazelcast at around 5 seconds (even with an initial priming send/reply sequence so it can cache its config).

in contrast, running with the Ignite Cluster Manager and all else the same,
time to send all 50k: 566ms
time from first received msg to last received message is 184ms

and with the jgroups Cluster Manager
time to send all 50k: 56ms
time from first received msg to last received message is 229ms

all these scale pretty linearly, 5MM with jgroups sends 11 seconds receives in ~27 seconds, and with ignite sends ~58 seconds receives ~27 seconds.

these all play out pretty much the same across multiple host machines in the same way too except for hazelcast which also only manages hundreds of messages a second across real boxes in my tests.

I got bored waiting for infinispan to complete 5MM but assume it would take ~1hr 40 mins.

this manager also logs a lot of entries as INFO where they should really be TRACE,
and it wont start even if I manually assign the clusterManager if I have any other managers on the classpath (no other managers have this issue). ie:

ClusterManager mgr = new InfinispanClusterManager();
VertxOptions options = new VertxOptions().setClusterManager(mgr);
...

not sure why performance is so slow for infinispan (or hazelcast), but given the sunsetting of jgroups and the ref to this as the project replacing it, I'm hoping it can be improved, or that I'm doing something dramatically wrong.

Cheers.

**Comment by jeacott1** [comment]
for reference, a pretty agricultural test - a few branches each testing a different clustermanager
https://github.com/jeacott1/vertx-clustermanager-simpletest

hoping I'm just doing something terribly wrong.

Cheers.

**Comment by tsegismont** [comment]
@jeacott1 can you elaborate about the log entries which should be at TRACE level? I suppose they come from Infinispan. In this case you can only configure that yourself with your logging tool.

As dicussed in the vert-x3/vertx-jgroups#30 the perf difference you're seeing is due to the subscription cache not being initialized. This is the same issue as vert-x3/vertx-hazelcast#73

As a workaround, you should send a single message in the beginning so that the cache gets initialized, then operate normally. My testing with your reproducer project shows that after cache setup vertx-infinispan operates faster than vertx-jgroups

**Comment by jeacott1** [comment]
@tsegismont i dont follow. I  Am sending an initial single message, waiting for the reply before sending the rest ofthe messages
what should i be doing more than this?

**Comment by tsegismont** [comment]
Replied in the other thread. Can we keep the discussion in that other
issue. Thanks.

2017-06-14 22:17 GMT+02:00 jeacott1 <notifications@github.com>:
