### ISSUE TITLE
localCosumer 100x slower than consumer in Clustered mode

### ISSUE THREAD

**Issue by oli-h** [vert-x3/vertx-infinispan#56]
Reproducer: https://gist.github.com/oli-h/e44c9e42033bd10945dc6c6afa460fcb

Tested with Vertx 3.5.3 and 3.5.0 on a Core i7-69xx:
- `consumer` handles 100'000 to 150'000 per second
- `localConsumer` is **factor 100 slower**: only ~1'500 per second can be delivered (and CPU-Load is high)

With Vertx 3.4.0 and 3.4.2 observations are different: Here, both types (consumer and localConsumer) are quite slow

Prior to 3.4.0 (e.g. 3.3.3) there seems to be no support for Infinispan-Cluster (or I didn't find the appropriate dependencies)

_Notes:_
- _I found #1764, but I think this was a different case as the performance panalty was only a few percent - not factor 100_
- _I also found https://github.com/eclipse/vert.x/commit/3ed3fea53990e31bdf63762c0bd67f1a0a5d6dc3 - this probably addresses the same basic issue, but from the sender's perspective_

(was https://github.com/eclipse-vertx/vert.x/issues/2617)

**Comment by tsegismont** [comment]
The difference is expected @oli-h 

The sender checks for a remote consumer before inspecting local registrations. As you noticed, in 3.6 you will be able to force local delivery in `DeliveryOptions`.

As for the difference between 3.5.x and 3.4.x, an issue has been fixed regarding the local cache of consumers (which was never stabilizing, in a scenario such as your benchmark, where a new message is sent before the cluster manager can find the remote consumer).

**Comment by oli-h** [comment]
Hm - but if the sender needs to send to a cluster-wide address, then he also needs to "check for remote consumer".
And 1500 per second seems to be ridiculous slow - especially as one expects a better performance with localConsumers. For my point of this makes localConsumers senseless.

And: Why not send to a localConsumer *before* "checking for remote consumer"? If we have a localConsumer - let it win. Why make the effort to "check for remote consumer" at all?

**Comment by tsegismont** [comment]
>Hm - but if the sender needs to send to a cluster-wide address, then he also needs to "check for remote consumer".

Not sure what you mean.

>And 1500 per second seems to be ridiculous slow - especially as one expects a better performance with localConsumers. For my point of this makes localConsumers senseless.

That's why the new delivery option was introduced in 3.6

>And: Why not send to a localConsumer before "checking for remote consumer"? If we have a localConsumer - let it win. Why make the effort to "check for remote consumer" at all?

Because the EventBus is supposed to distribute load across regular consumers on all nodes. Again if you want to favor local consumer, use the new option in 3.6.
