### ISSUE TITLE
Upgrade to Infinispan 10

### ISSUE THREAD

**Issue by tsegismont** [vert-x3/vertx-infinispan#70]
Infinispan 10 is planned for October 2019.

In the meantime we can start a branch to test with beta versions.

**Comment by eckig** [comment]
Any progress on this?

**Comment by karesti** [comment]
@tsegismont release is out

**Comment by tsegismont** [comment]
Thanks for the heads up @karesti !

@eckig we are working on a cluster SPI redesign in Vert.x core. That will impact this cluster manager implementation and this is why I'm waiting to perform the upgrade.

**Comment by pcariel** [comment]
Any progress on this?

**Comment by tsegismont** [comment]
We're waiting for the clustering SPI update PR to be merged first. I plan
to have the ISPN update ready for the next Vert.x 4 milestone
