### ISSUE TITLE
Infinispan Web Session Store

### ISSUE THREAD

**Issue by tsegismont** [vert-x3/vertx-infinispan#81]
Vert.x Web has an SPI for web session data storage.

Infinispan is a good fit for this use case.

**Comment by pmlopes** [comment]
How different would this be from the already available `ClusteredSessionStore` store? If vertx cluster is enabled it should probably be the same, if not, then this would join a cluster somewhere i guess.

**Comment by tsegismont** [comment]
It would not use ISPN embedded but rather an ISPN Client
